# fly.toml app configuration file generated for gymmy-gnome-bot on 2024-12-14T17:43:21+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "gymmy-gnome-bot"
kill_signal = "SIGINT"
kill_timeout = 5

[processes]
app = "node ./dist/index.js"

# Adjust the NODE_ENV environment variable to suppress the warning
[build.args]
NODE_ENV = "production"

[build]
builder = "heroku/buildpacks:20"

# Simply omitting the whole of the [[services]] section since we are not listening to HTTP.